### ISSUE TITLE
user_assessments endpoint throws 500s

### ISSUE THREAD

**Issue by doodles526** [prehire/interviewed-api#1]
I'm trying to use the interviewed-api. 
```
curl "https://interviewed-api.com/v1/candidacies/<id>/user_assessments/<id>?api_key=<API_KEY>" | json_pp
{
   "error" : "Internal Server Error",
   "status" : "500"
}
```

It looks like the API is in beta or alpha for now. But thought I would let you know. Everything else works well though

**Comment by oshea** [comment]
Thanks for the heads up. We are looking into it now.

**Comment by jono** [comment]
@doodles526 Issue resolved.

**Comment by doodles526** [comment]
Nice! Thanks for the quick turnaround!
